[install]
is_configured = true
build = 1

[ui]
is_visible = true
label = Trafficking Initiative 2026

[launcher]
author = ARDOT
description = ARDOT Trafficking Initiative 2026 - Anti-trafficking data analysis and visualization
version = 1.0.0

[package]
id = ARDOT
check_for_updates = false
