# Saved searches, reports, and alerts for ARDOT
# Add saved searches below following this format:
#
# [Search Name]
# search = <SPL query>
# dispatch.earliest_time = -24h@h
# dispatch.latest_time = now
# cron_schedule = 0 */6 * * *
# enableSched = 1
# is_visible = true
