# Field transforms and lookup definitions for ARDOT
# Add lookup table definitions and field transforms below
#
# [lookup_name]
# filename = lookup_file.csv
# default_match = NOT_FOUND
# min_matches = 1
# max_matches = 1
